version: '3'
services:
  web:
    build: ./docker/nginx
    volumes:
      - ./src:/var/www/html
    ports:
      - 18080:80
    depends_on:
      - php
      - db
    networks:
      - internal
      - horse-network

  db:
    image: mariadb:10.5
    restart: always
    ports:
      - 3308:13306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:cached
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d

  php:
    build: ./docker/php
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    networks:
      - internal
      - horse-network

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - "./docker/redis:/data"
    networks:
      - horse-network

networks:
  horse-network:
    external: true
  internal:
    driver: bridge